<?php

namespace ContainerM4nlNDJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CartController' shared autowired service.
     *
     * @return \App\Controller\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/CartController.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Cart/Service/CartService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Cart/Repository/CartRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemory/InMemoryCartRepository.php';

        return $container->services['App\\Controller\\CartController'] = new \App\Controller\CartController(new \App\Domain\Cart\Service\CartService(new \App\Infrastructure\Persistence\InMemory\InMemoryCartRepository()));
    }
}
