<?php

namespace ContainerM4nlNDJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProductController' shared autowired service.
     *
     * @return \App\Controller\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ProductController.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Product/Repository/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemory/InMemoryProductRepository.php';

        return $container->services['App\\Controller\\ProductController'] = new \App\Controller\ProductController(($container->privates['App\\Infrastructure\\Persistence\\InMemory\\InMemoryProductRepository'] ?? ($container->privates['App\\Infrastructure\\Persistence\\InMemory\\InMemoryProductRepository'] = new \App\Infrastructure\Persistence\InMemory\InMemoryProductRepository())));
    }
}
