<?php

namespace ContainerM4nlNDJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSellerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SellerController' shared autowired service.
     *
     * @return \App\Controller\SellerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/SellerController.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/User/Service/SellerService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/User/Repository/SellerRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemory/InMemorySellerRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Product/Repository/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InMemory/InMemoryProductRepository.php';

        return $container->services['App\\Controller\\SellerController'] = new \App\Controller\SellerController(new \App\Domain\User\Service\SellerService(new \App\Infrastructure\Persistence\InMemory\InMemorySellerRepository(), ($container->privates['App\\Infrastructure\\Persistence\\InMemory\\InMemoryProductRepository'] ?? ($container->privates['App\\Infrastructure\\Persistence\\InMemory\\InMemoryProductRepository'] = new \App\Infrastructure\Persistence\InMemory\InMemoryProductRepository()))));
    }
}
